services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  app-backend:
    container_name: repair-backend
    image: app
    restart: on-failure
    ports:
      - "8000:8000"
    build: ./backend
    volumes:
      - .:/backend
    depends_on:
      - mongo_db
  
  app-frontend:
    container_name: repair-frontend
    image: app_vue
    restart: on-failure
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"


volumes:
  mongo:
        
        