services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  app:
    container_name: repair-app
    image: app
    restart: on-failure
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongo_db


volumes:
  mongo:
        
        