services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "6000:27017"
    networks:
      - custom

  app:
    container_name: repair-backend
    image: app
    restart: on-failure
    environment:
      - MONGODB_URL=mongodb://mongo_db/repair_db
    ports:
      - "8000:8000"
    networks:
      - custom
    build: ..
    volumes:
      - .:/backend
    command: uvicorn main:backend --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo_db

        
        
networks:
  custom:
    driver: bridge
        
        